"""initial schema

Revision ID: 8b1180f2386c
Revises: 
Create Date: 2026-03-25 15:13:21.263718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1180f2386c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('backup', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('hardware', sa.Text(), nullable=False),
    sa.Column('framework', sa.Text(), nullable=False),
    sa.Column('precision', sa.Text(), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('seqlens', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('pic', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('story_label', sa.Text(), nullable=True),
    sa.Column('accuracy_status', sa.Text(), nullable=False),
    sa.Column('nv_tps', sa.Float(), nullable=True),
    sa.Column('amd_tps', sa.Float(), nullable=True),
    sa.Column('dl_perf_published', sa.Text(), nullable=True),
    sa.Column('infmax_submitted', sa.Text(), nullable=True),
    sa.Column('nvmax_recipe_url', sa.Text(), nullable=True),
    sa.Column('ibdb_link', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', 'hardware', 'framework', 'precision', 'scenario', 'seqlens', name='uq_workload_identity')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workload_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('user_email', sa.Text(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workload_id'], ['workloads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workload_id', sa.Integer(), nullable=False),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Text(), nullable=False),
    sa.Column('uploaded_by_email', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workload_id'], ['workloads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_versions')
    op.drop_table('audit_log')
    op.drop_table('workloads')
    op.drop_table('team_functions')
    # ### end Alembic commands ###
